// app/styles.js

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        top: 40,
        flex: 1,
        padding: 20,
        backgroundColor: '#f5f6fa',
    },
    input: {
        height: 50,
        borderWidth: 1,
        borderColor: '#e5e5ea',
        borderRadius: 12,
        paddingHorizontal: 16,
        fontSize: 16,
        color: '#1c1c1e',
        backgroundColor: 'white',
        marginBottom: 15,
    },
    addTaskButton: {
        backgroundColor: '#007aff',
        borderRadius: 25,
        paddingVertical: 15,
        paddingHorizontal: 30,
        marginVertical: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    addTaskButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
    conflictAlert: {
        backgroundColor: '#ffcccc',
        padding: 15,
        borderRadius: 10,
        margin: 10,
    },
    conflictText: {
        color: '#cc0000',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    taskItem: {
        backgroundColor: 'white',
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 2,
    },
    taskText: {
        fontSize: 16,
        marginBottom: 8,
    },
    taskDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 4,
    },
    timeRangeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    timeRangeText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },
    categoryLabel: {
        padding: 5,
        borderRadius: 5,
        color: 'white',
        fontWeight: 'bold',
    },
    timeText: {
        color: '#666',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
        backgroundColor: 'white',
        margin: 20,
        borderRadius: 10,
        padding: 20,
    },
    editModalContent: {
        backgroundColor: 'white',
        margin: 20,
        borderRadius: 20,
        padding: 25,
        maxHeight: '85%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#007aff',
        marginBottom: 25,
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    feedbackTriggerButton: {
        backgroundColor: '#007aff',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 10,
        marginTop: 10,
        alignSelf: 'flex-start',
    },
    feedbackTriggerButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    feedbackModalContent: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 30,
        marginHorizontal: 20,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    feedbackModalTitle: {
        fontSize: 22,
        fontWeight: '700',
        marginBottom: 20,
        color: '#333',
    },
    feedbackInfoText: {
        fontSize: 16,
        marginBottom: 15,
        textAlign: 'center',
        color: '#555',
    },
    feedbackQuestion: {
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 20,
        color: '#333',
    },
    feedbackButtonRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 20,
    },
    feedbackButton: {
        backgroundColor: '#007aff',
        borderRadius: 10,
        paddingVertical: 15,
        paddingHorizontal: 25,
        minWidth: 120,
        alignItems: 'center',
        marginHorizontal: 10,
    },
    feedbackButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
    },
    feedbackCancelButton: {
        marginTop: 10,
    },
    feedbackCancelButtonText: {
        color: '#007aff',
        fontSize: 16,
        fontWeight: '500',
    },
    // In styles.js
    pickerModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'flex-end', // Align content at bottom
        alignItems: 'stretch', // Stretch width
    },
    // In styles.js
    pickerModalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 24, // Rounded top corners
        borderTopRightRadius: 24,
        padding: 20,
        maxHeight: '50%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
    },
    // In styles.js
    pickerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderBottomWidth: 1, // Add separator
        borderBottomColor: '#f0f0f5',
    },
    pickerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1c1c1e',
    },
    pickerDoneButton: {
        color: '#007aff',
        fontSize: 17,
        fontWeight: '600',
    },
    // Add to styles.js
    pickerItem: {
        fontSize: 18,
        color: '#1c1c1e',
    },
    selectionButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#e5e5ea',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    selectionButtonText: {
        fontSize: 16,
        color: '#1c1c1e',
        fontWeight: '500',
    },
    selectionButtonIcon: {
        fontSize: 18,
        color: '#8e8e93',
        marginLeft: 8,
    },
    recurrenceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 15,
    },
    recurrenceInput: {
        flex: 1,
        bottom: 5,
        height: 48,
        borderWidth: 1,
        borderColor: '#e5e5ea',
        borderRadius: 12,
        paddingHorizontal: 16,
        fontSize: 16,
        color: '#1c1c1e',
        backgroundColor: 'white',
    },
    daysGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 7,
        marginBottom: 15,
        justifyContent: 'space-between',
    },
    dayButton: {
        width: 70,
        height: 70,
        borderRadius: 40,
        borderWidth: 1.5,
        borderColor: '#e5e5ea',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
    },
    selectedDay: {
        backgroundColor: '#007aff',
        borderColor: '#007aff',
    },
    dayText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#8e8e93',
    },
    selectedDayText: {
        color: 'white',
    },
    label: {
        fontSize: 14,
        fontWeight: '500',
        color: '#8e8e93',
        marginBottom: 8,
        marginTop: 15,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1c1c1e',
        marginBottom: 15,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f5',
    },
    calendarTheme: {
        backgroundColor: '#ffffff',
        calendarBackground: '#ffffff',
        textSectionTitleColor: '#8e8e93',
        selectedDayBackgroundColor: '#007aff',
        selectedDayTextColor: '#ffffff',
        todayTextColor: '#007aff',
        dayTextColor: '#1c1c1e',
        textDisabledColor: '#d1d1d6',
        arrowColor: '#007aff',
        monthTextColor: '#1c1c1e',
        indicatorColor: '#007aff',
        textDayFontWeight: '500',
        textMonthFontWeight: '600',
        textDayHeaderFontWeight: '500',
        textDayFontSize: 14,
        textMonthFontSize: 16,
        textDayHeaderFontSize: 12,
    },
    scanButton: {
        backgroundColor: '#FF6B6B',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 25,
        marginVertical: 10,
    },
    scanButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
    categoryButton: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    categoryText: {
        fontSize: 16,
        textAlign: 'center',
    },
    taskList: {
        marginTop: 20,
    },
    dateText: {
        color: '#666',
        fontWeight: '500',
    },
    deleteButton: {
        marginTop: 1,
        backgroundColor: '#ff3b30',
        borderRadius: 8,
        padding: 12,
        alignItems: 'center',
    },
    deleteButtonText: {
        color: 'white',
        fontWeight: 'bold',
    },
    tabBar: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        position: 'absolute',
        bottom: 40,
        left: 0,
        right: 0,
        backgroundColor: '#ffffff',
        paddingVertical: 30,
        borderTopWidth: 1,
        borderTopColor: '#ccc',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
    },
    tabButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 30,
        backgroundColor: '#f7f7f7',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    activeTab: {
        backgroundColor: '#007aff',
        transform: [{ scale: 1.1 }],
        shadowColor: '#007aff',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
        elevation: 5,
    },
    tabText: {
        color: '#333',
        fontWeight: '600',
        fontSize: 14,
        transition: 'color 0.2s',
    },
    activeTabText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
    },
    sectionHeader: {
        fontSize: 16,
        fontWeight: 'bold',
        backgroundColor: '#000',
        color: '#fff',
        paddingVertical: 8,
        paddingHorizontal: 16,
        marginTop: 15,
        marginBottom: 3,
        marginHorizontal: 0,
        borderRadius: 8,
        textAlign: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 2,
    },
    calendarContainer: {
        flex: 1,
        marginBottom: 60,
    },
    calendarDayContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        width: 36,
        height: 36,
        borderRadius: 18,
    },
    timePickerContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginVertical: 15,
        backgroundColor: '#f8f8fa',
        borderRadius: 12,
        padding: 10,
    },
    pickerColumn: {
        alignItems: 'center',
        flex: 1,
    },
    pickerLabel: {
        fontSize: 12,
        fontWeight: '500',
        color: '#8e8e93',
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    closeButton: {
        position: 'absolute',
        right: 15,
        top: 15,
        padding: 5,
    },
    closeButtonText: {
        fontSize: 24,
        color: '#666',
    },
    formActions: {
        marginTop: 25,
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 15,
    },
    actionButton: {
        flex: 1,
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#007aff',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 3,
    },
    saveButton: {
        backgroundColor: '#007aff',
    },
    actionButtonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 16,
        letterSpacing: 0.5,
    },
    // NEW: Style for button row that holds the ALIGN PAPER and ALIGN SLEEP buttons
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginVertical: 10,
    },
});

export const getCategoryColor = (category) => {
    const colors = {
        STUDY: '#ff7675',
        ENTERTAINMENT: '#74b9ff',
        WORK: '#55efc4',
        EVENT: '#a29bfe',
        ERRAND: '#ffeaa7',
        EXERCISE: '#fd79a8',
        OTHER: '#464545',
        'HOUSEHOLD CHORE': '#81ecec',
    };
    return colors[category] || '#dfe6e9';
};
